### ISSUE TITLE
Issues encountered while setting up.

### ISSUE THREAD

**Issue by samdasoxide** [rjadr/django-pdf-flipbook#1]
Thanks for your wonderful work on creating this awesome app I truly appreciate.  But encountered some hurdles that I managed to get through whilst setting up. This may help (especially the novice django developers) with debugging.

1. I noticed that you didn't have migrations for the app. So I had to a  `$ ./manage.py makemigrations`. Which brought up the issue below (issue 2). 

2. I had issues installing Imagemagick on Mac OS X 10.10.5 (worked fine on Ubuntu 16.04). Got the following error when trying to `./manage.py makemigrations` yet I had Imagemagick installed
```
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
    Try to install: brew install freetype imagemagick
```
This SO answer fixed it: https://stackoverflow.com/a/41772062

3. After fixing the above, trying to `./manage.py makemigrations` I got the following error:
`valueError: Cannot serialize: <flipbook.models.FileValidator object at 0x112603908>
There are some values Django cannot serialize into migration files.
For more, see https://docs.djangoproject.com/en/1.11/topics/migrations/#migration-serializing`

For this, I imported `from django.utils.deconstruct import deconstructible` and added a `@deconstructor` decorator to the `FileValidator` class.

4. Add url for flipbook to project root url
For that I did a 
```python
from flipbook import urls as flipbook_urls

urlpatterns = [
# other urls
 url(r'^flipbook/', include(flipbook_urls)),
]
```

5. When trying to upload a test document it failed since I didn't have `ghostscript` installed.
You can also add to the requirements for Mac OS X 10.10.5 (already had `gs` on Ubuntu 16.04)
For this I did a
```bash
$ brew install ghostscript
```

6. Change the template in `view.py` to use the `index-dflip.html` if you using  `dFlip PDF FlipBook jQuery Plugin`.

7. `CMS_TEMPLATE` = base.html. You could mention this. Took sometime to wrap my mind around.  

Hope this will be helpful.

**Comment by rjadr** [comment]
Thanks for the feedback! I finally found some time to improve the readme, taking your comments into account. I've also simplified the file validator, solving the serialization error. Everything works now on Django 2.2.
